#pragma once

#include "Packet.h"
#include "PacketTest.h"
#include "PacketCreateGameAnswer.h"
#include "PacketCreateGameRequest.h"
#include "PacketGetGamesAnswer.h"
#include "PacketGetGamesRequest.h"
#include "PacketJoinGameAnswer.h"
#include "PacketJoinGameRequest.h"
#include "PacketClientDisconnect.h"
#include "PacketLeaveGameAnswer.h"
#include "PacketLeaveGameRequest.h"
#include "PacketDeleteGameRequest.h"
#include "PacketAck.h"
#include "PacketClientConnected.h"
#include "PacketPlayerReady.h"
#include "PacketPlayerNotReady.h"
#include "PacketStartGame.h"
#include "PacketConnectedUdpAnswer.h"
#include "PacketNewPlayerJoinGame.h"
#include "PacketUpdateHealth.h"
#include "PacketUpdateMovementAnswer.h"
#include "PacketUpdateMovementRequest.h"
#include "PacketGameStarted.h"

